services:
  INSTANCE_LABEL-widenbot-client:
    container_name: INSTANCE_LABEL-widenbot-client
    build: .
    ports:
      - CLIENT_PORT:CLIENT_PORT
    networks:
      - INSTANCE_LABEL-widenbot-net

networks:
  INSTANCE_LABEL-widenbot-net:
    name: INSTANCE_LABEL-widenbot-net
    external: true
