services:
  INSTANCE_LABEL-client:
    container_name: INSTANCE_LABEL-client
    build: .
    ports:
      - CLIENT_PORT:CLIENT_PORT
    networks:
      - INSTANCE_LABEL-net

networks:
  INSTANCE_LABEL-net:
    name: INSTANCE_LABEL-net
    external: true
