services:
  server:
    # Lavalink v4
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: widenbot-server
    restart: unless-stopped
    environment:
      # Java options
      - _JAVA_OPTIONS=-Xmx6G
      # Lavalink server port
      - SERVER_PORT=2333
      # Lavalink password
      - LAVALINK_SERVER_PASSWORD=<LAVALINK_PASSWORD>
    volumes:
      # Mount application.yml from the same directory
      - ./application.yml:/opt/Lavalink/application.yml
      # Persist plugins between restarts
      - ./plugins/:/opt/Lavalink/plugins/
    networks:
      # Use the lavalink network defined below so client container can see it
      - lavalink
    expose:
      # Expose port 2333 for the client
      - 2333
    #ports:
      #  # you only need this if you want to make your lavalink accessible from outside of containers
      #- "2333:2333"
networks:
  # Create network so the client can talk to the server
  lavalink:
    name: lavalink
